# Databricks App runtime. Python deps: requirements.txt (fastapi, uvicorn, databricks-sdk are pre-installed).
# Required env: PGAPPNAME (below), DATABRICKS_HOST, DATABRICKS_WAREHOUSE_ID, DATABRICKS_TOKEN. See docs/1_DEPLOYMENTS.md.
command:
  - uvicorn
  - "payment_analysis.backend.app:app"
  - --host
  - "0.0.0.0"
  - --workers
  - "1"
env:
  - name: PYTHONPATH
    value: src
  - name: PGAPPNAME
    value: payment-analysis-db-dev
