# Databricks App execution (app.yaml). Required at project root.
# Docs: https://docs.databricks.com/aws/en/dev-tools/databricks-apps/app-runtime
# App definition (resources, bindings): resources/fastapi_app.yml. When deployed, the platform runs this in source_code_path and proxies traffic to the app.
# Environment variables: defined below in env (not in Compute → Apps → Edit UI). Redeploy bundle to apply changes.
# User auth: open from Compute → Apps → payment-analysis so the platform forwards your token (x-forwarded-access-token).
# Lakebase: LAKEBASE_* below; DATABRICKS_WAREHOUSE_ID from sql-warehouse binding; DATABRICKS_CLIENT_ID/SECRET injected by platform.
command:
  - uvicorn
  - payment_analysis.backend.app:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"
env:
  - name: PYTHONPATH
    value: src
  # Note: These values should match the bundle variables in databricks.yml.
  # They are set here because app.yml is consumed by the Databricks App runtime,
  # not by the DAB engine, so ${var.*} interpolation is not available.
  - name: LAKEBASE_PROJECT_ID
    value: payment-analysis-db
  - name: LAKEBASE_BRANCH_ID
    value: production
  - name: LAKEBASE_ENDPOINT_ID
    value: primary
  # Use AgentBricks orchestrator for chat (Model Serving). Omit or set empty to use Job 6 (custom Python).
  - name: ORCHESTRATOR_SERVING_ENDPOINT
    value: payment-analysis-orchestrator
