# Runtime spec (same as app.yaml). Required at root for "error loading app spec from app.yml".
# PGAPPNAME must match var.lakebase_instance_name (dev: payment-analysis-db-dev).
command:
  - uvicorn
  - app:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"
env:
  - name: PYTHONPATH
    value: src
  - name: PGAPPNAME
    value: payment-analysis-db-dev
