# Databricks App runtime. Python deps: requirements.txt (fastapi, uvicorn, databricks-sdk are pre-installed).
# Set PGAPPNAME to the Lakebase instance name (dev: payment-analysis-db-dev) for UI CRUD and ML features.
command:
  - uvicorn
  - payment_analysis.backend.app:app
  - --host
  - "0.0.0.0"
  - --workers
  - "1"
env:
  - name: PYTHONPATH
    value: src
  # Lakebase instance for rules, experiments, incidents, ML features (dev)
  - name: PGAPPNAME
    value: payment-analysis-db-dev
