# Databricks App runtime. Python deps: requirements.txt (fastapi, uvicorn, databricks-sdk are pre-installed).
# Optional: set PGAPPNAME to Lakebase instance name for rules/experiments/incidents DB.
command:
  - uvicorn
  - payment_analysis.backend.app:app
  - --host
  - "0.0.0.0"
  - --workers
  - "1"
env:
  - name: PYTHONPATH
    value: src
