# Runtime spec. Keep app.yml in sync (runtime may load app.yml first).
# See https://apps-cookbook.dev/docs/fastapi/getting_started/create
# PGAPPNAME must match var.lakebase_instance_name (dev: payment-analysis-db-dev).
command:
  - uvicorn
  - app:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"
env:
  - name: PYTHONPATH
    value: src
  - name: PGAPPNAME
    value: payment-analysis-db-dev
