# Runtime spec (same as app.yaml). Required at root for "error loading app spec from app.yml".
# DBA definition lives in resources/fastapi_app.yml (included from databricks.yml). This file only defines how to run the container.
# When deployed as a Databricks App, the platform runs this in the workspace folder (source_code_path); "Uvicorn running on http://0.0.0.0:8000" in logs is expected — the app binds to that address and the platform proxies traffic to it (not localhost).
# Open the app from Workspace → Compute → Apps → payment-analysis so the platform forwards your token (no DATABRICKS_TOKEN needed). Set PGAPPNAME and DATABRICKS_WAREHOUSE_ID in the app Environment; DATABRICKS_HOST is optional when opened from Apps.
command:
  - uvicorn
  - payment_analysis.backend.app:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"
env:
  - name: PYTHONPATH
    value: src
  - name: PGAPPNAME
    value: payment-analysis-db-dev
