"""
Package version.

In APX builds, `src/payment_analysis/_version.py` is generated by the build hook.
In clean checkouts (or certain tooling flows), that file may not exist yet.
"""

try:
    from ._version import version as __version__
except Exception:
    # Safe fallback for local tooling / typechecking
    __version__ = "0.0.0"
