# =============================================================================
# Databricks App - Payment Approval Optimization Platform
# =============================================================================
# Deploys the app (FastAPI + React UI) to Databricks Apps. After bundle deploy,
# run the app via Workspace → Apps or: databricks bundle run payment_analysis_app -t dev
# App URL is shown in bundle summary or in Workspace → Apps.
# Name: payment-analysis. Source folder: project root (source_code_path: ..).
#
# Bound resources (include if required for the app):
#   - database: Lakebase (rules, experiments, incidents, ML features)
#   - sql_warehouse: analytics, app_config, gold views
#   - genie_space: when var.genie_space_id is set (create space first, then set variable)
#   - job (x12): Setup & Run, agents, streaming, Genie sync
#   - serving_endpoint (x4): when resources/model_serving.yml is included
#   - uc_securable (reports volume): app/jobs may read or write reports
#   - secret: optional; add scope/key below if the app needs secrets
# Not in bundle app.resources: dashboards (link by URL), MLflow experiment (used by job; add in UI if needed),
#   vector search index, UC function, UC connection (add in Apps UI if needed).
# =============================================================================

resources:
  apps:
    payment_analysis_app:
      name: payment-analysis
      source_code_path: ..
      description: Payment Approval Optimization Platform – dashboards, rules, decisioning, ML models, and agent jobs.
      resources:
        - name: database
          description: Lakebase instance for rules, experiments, incidents, ML features
          database:
            instance_name: ${var.lakebase_instance_name}
            database_name: ${var.lakebase_database_name}
            permission: CAN_CONNECT_AND_CREATE
        - name: sql-warehouse
          description: SQL warehouse for analytics, app_config, gold views
          sql_warehouse:
            id: ${resources.sql_warehouses.payment_analysis_warehouse.id}
            permission: CAN_USE
        # Genie space: uses existing "Approvals domain expert"; set var.genie_space_id to that space's ID (from Genie UI). Change name/ID when a new Genie space is created.
        - name: genie-space
          description: Genie space for natural language analytics (Ask Data)
          genie_space:
            name: "Approvals domain expert"
            space_id: ${var.genie_space_id}
            permission: CAN_RUN
        # Optional secret: uncomment and set scope/key if the app needs secrets
        # - name: app-secrets
        #   description: Secret scope for API keys or other sensitive config
        #   secret:
        #     scope: "payment-analysis"
        #     key: "api-key"
        #     permission: READ
        - name: volume-reports
          description: UC volume for reports and Genie config
          uc_securable:
            securable_type: VOLUME
            securable_full_name: "${var.catalog}.${var.schema}.reports"
            permission: READ_VOLUME
        # Jobs used by UI (Setup & Run, agents, streaming, Genie sync)
        - name: job-simulator
          description: Transaction stream simulator
          job:
            id: ${resources.jobs.transaction_stream_simulator.id}
            permission: CAN_MANAGE_RUN
        - name: job-continuous-processor
          description: Continuous stream processor
          job:
            id: ${resources.jobs.continuous_stream_processor.id}
            permission: CAN_MANAGE_RUN
        - name: job-gold-views
          description: Create gold views
          job:
            id: ${resources.jobs.create_gold_views_job.id}
            permission: CAN_MANAGE_RUN
        - name: job-train-ml
          description: Train ML models
          job:
            id: ${resources.jobs.train_ml_models_job.id}
            permission: CAN_MANAGE_RUN
        - name: job-test-agent
          description: Test agent framework
          job:
            id: ${resources.jobs.test_agent_framework_job.id}
            permission: CAN_MANAGE_RUN
        - name: job-orchestrator-agent
          description: Orchestrator agent
          job:
            id: ${resources.jobs.orchestrator_agent_job.id}
            permission: CAN_MANAGE_RUN
        - name: job-smart-routing-agent
          description: Smart routing agent
          job:
            id: ${resources.jobs.smart_routing_agent_job.id}
            permission: CAN_MANAGE_RUN
        - name: job-smart-retry-agent
          description: Smart retry agent
          job:
            id: ${resources.jobs.smart_retry_agent_job.id}
            permission: CAN_MANAGE_RUN
        - name: job-decline-analyst-agent
          description: Decline analyst agent
          job:
            id: ${resources.jobs.decline_analyst_agent_job.id}
            permission: CAN_MANAGE_RUN
        - name: job-risk-assessor-agent
          description: Risk assessor agent
          job:
            id: ${resources.jobs.risk_assessor_agent_job.id}
            permission: CAN_MANAGE_RUN
        - name: job-performance-recommender-agent
          description: Performance recommender agent
          job:
            id: ${resources.jobs.performance_recommender_agent_job.id}
            permission: CAN_MANAGE_RUN
        - name: job-genie-sync
          description: Genie space sync
          job:
            id: ${resources.jobs.genie_sync_job.id}
            permission: CAN_MANAGE_RUN
        # Model serving endpoints (require resources/model_serving.yml in databricks.yml)
        - name: serving-approval-propensity
          description: Approval propensity model endpoint
          serving_endpoint:
            name: "approval-propensity-${var.environment}"
            permission: CAN_QUERY
        - name: serving-risk-scoring
          description: Risk scoring model endpoint
          serving_endpoint:
            name: "risk-scoring-${var.environment}"
            permission: CAN_QUERY
        - name: serving-smart-routing
          description: Smart routing model endpoint
          serving_endpoint:
            name: "smart-routing-${var.environment}"
            permission: CAN_QUERY
        - name: serving-smart-retry
          description: Smart retry model endpoint
          serving_endpoint:
            name: "smart-retry-${var.environment}"
            permission: CAN_QUERY
      # PGAPPNAME is set in app.yaml for Lakebase (e.g. payment-analysis-db-dev).
