/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarIncidentsRouteImport } from './../routes/_sidebar/incidents'
import { Route as SidebarExperimentsRouteImport } from './../routes/_sidebar/experiments'
import { Route as SidebarDeclinesRouteImport } from './../routes/_sidebar/declines'
import { Route as SidebarDecisioningRouteImport } from './../routes/_sidebar/decisioning'
import { Route as SidebarDashboardRouteImport } from './../routes/_sidebar/dashboard'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarIncidentsRoute = SidebarIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarExperimentsRoute = SidebarExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDeclinesRoute = SidebarDeclinesRouteImport.update({
  id: '/declines',
  path: '/declines',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDecisioningRoute = SidebarDecisioningRouteImport.update({
  id: '/decisioning',
  path: '/decisioning',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDashboardRoute = SidebarDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/decisioning': typeof SidebarDecisioningRoute
  '/declines': typeof SidebarDeclinesRoute
  '/experiments': typeof SidebarExperimentsRoute
  '/incidents': typeof SidebarIncidentsRoute
  '/profile': typeof SidebarProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/decisioning': typeof SidebarDecisioningRoute
  '/declines': typeof SidebarDeclinesRoute
  '/experiments': typeof SidebarExperimentsRoute
  '/incidents': typeof SidebarIncidentsRoute
  '/profile': typeof SidebarProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/dashboard': typeof SidebarDashboardRoute
  '/_sidebar/decisioning': typeof SidebarDecisioningRoute
  '/_sidebar/declines': typeof SidebarDeclinesRoute
  '/_sidebar/experiments': typeof SidebarExperimentsRoute
  '/_sidebar/incidents': typeof SidebarIncidentsRoute
  '/_sidebar/profile': typeof SidebarProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/decisioning'
    | '/declines'
    | '/experiments'
    | '/incidents'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/decisioning'
    | '/declines'
    | '/experiments'
    | '/incidents'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/dashboard'
    | '/_sidebar/decisioning'
    | '/_sidebar/declines'
    | '/_sidebar/experiments'
    | '/_sidebar/incidents'
    | '/_sidebar/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/incidents': {
      id: '/_sidebar/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof SidebarIncidentsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/experiments': {
      id: '/_sidebar/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof SidebarExperimentsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/declines': {
      id: '/_sidebar/declines'
      path: '/declines'
      fullPath: '/declines'
      preLoaderRoute: typeof SidebarDeclinesRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/decisioning': {
      id: '/_sidebar/decisioning'
      path: '/decisioning'
      fullPath: '/decisioning'
      preLoaderRoute: typeof SidebarDecisioningRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/dashboard': {
      id: '/_sidebar/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SidebarDashboardRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarDashboardRoute: typeof SidebarDashboardRoute
  SidebarDecisioningRoute: typeof SidebarDecisioningRoute
  SidebarDeclinesRoute: typeof SidebarDeclinesRoute
  SidebarExperimentsRoute: typeof SidebarExperimentsRoute
  SidebarIncidentsRoute: typeof SidebarIncidentsRoute
  SidebarProfileRoute: typeof SidebarProfileRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarDashboardRoute: SidebarDashboardRoute,
  SidebarDecisioningRoute: SidebarDecisioningRoute,
  SidebarDeclinesRoute: SidebarDeclinesRoute,
  SidebarExperimentsRoute: SidebarExperimentsRoute,
  SidebarIncidentsRoute: SidebarIncidentsRoute,
  SidebarProfileRoute: SidebarProfileRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
