/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarSmartRetryRouteImport } from './../routes/_sidebar/smart-retry'
import { Route as SidebarSmartCheckoutRouteImport } from './../routes/_sidebar/smart-checkout'
import { Route as SidebarSetupRouteImport } from './../routes/_sidebar/setup'
import { Route as SidebarRulesRouteImport } from './../routes/_sidebar/rules'
import { Route as SidebarReasonCodesRouteImport } from './../routes/_sidebar/reason-codes'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarNotebooksRouteImport } from './../routes/_sidebar/notebooks'
import { Route as SidebarModelsRouteImport } from './../routes/_sidebar/models'
import { Route as SidebarIncidentsRouteImport } from './../routes/_sidebar/incidents'
import { Route as SidebarExperimentsRouteImport } from './../routes/_sidebar/experiments'
import { Route as SidebarDeclinesRouteImport } from './../routes/_sidebar/declines'
import { Route as SidebarDecisioningRouteImport } from './../routes/_sidebar/decisioning'
import { Route as SidebarDashboardsRouteImport } from './../routes/_sidebar/dashboards'
import { Route as SidebarDashboardRouteImport } from './../routes/_sidebar/dashboard'
import { Route as SidebarAiAgentsRouteImport } from './../routes/_sidebar/ai-agents'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarSmartRetryRoute = SidebarSmartRetryRouteImport.update({
  id: '/smart-retry',
  path: '/smart-retry',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarSmartCheckoutRoute = SidebarSmartCheckoutRouteImport.update({
  id: '/smart-checkout',
  path: '/smart-checkout',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarSetupRoute = SidebarSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarRulesRoute = SidebarRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarReasonCodesRoute = SidebarReasonCodesRouteImport.update({
  id: '/reason-codes',
  path: '/reason-codes',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarNotebooksRoute = SidebarNotebooksRouteImport.update({
  id: '/notebooks',
  path: '/notebooks',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarModelsRoute = SidebarModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarIncidentsRoute = SidebarIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarExperimentsRoute = SidebarExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDeclinesRoute = SidebarDeclinesRouteImport.update({
  id: '/declines',
  path: '/declines',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDecisioningRoute = SidebarDecisioningRouteImport.update({
  id: '/decisioning',
  path: '/decisioning',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDashboardsRoute = SidebarDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarDashboardRoute = SidebarDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarAiAgentsRoute = SidebarAiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agents': typeof SidebarAiAgentsRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/dashboards': typeof SidebarDashboardsRoute
  '/decisioning': typeof SidebarDecisioningRoute
  '/declines': typeof SidebarDeclinesRoute
  '/experiments': typeof SidebarExperimentsRoute
  '/incidents': typeof SidebarIncidentsRoute
  '/models': typeof SidebarModelsRoute
  '/notebooks': typeof SidebarNotebooksRoute
  '/profile': typeof SidebarProfileRoute
  '/reason-codes': typeof SidebarReasonCodesRoute
  '/rules': typeof SidebarRulesRoute
  '/setup': typeof SidebarSetupRoute
  '/smart-checkout': typeof SidebarSmartCheckoutRoute
  '/smart-retry': typeof SidebarSmartRetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agents': typeof SidebarAiAgentsRoute
  '/dashboard': typeof SidebarDashboardRoute
  '/dashboards': typeof SidebarDashboardsRoute
  '/decisioning': typeof SidebarDecisioningRoute
  '/declines': typeof SidebarDeclinesRoute
  '/experiments': typeof SidebarExperimentsRoute
  '/incidents': typeof SidebarIncidentsRoute
  '/models': typeof SidebarModelsRoute
  '/notebooks': typeof SidebarNotebooksRoute
  '/profile': typeof SidebarProfileRoute
  '/reason-codes': typeof SidebarReasonCodesRoute
  '/rules': typeof SidebarRulesRoute
  '/setup': typeof SidebarSetupRoute
  '/smart-checkout': typeof SidebarSmartCheckoutRoute
  '/smart-retry': typeof SidebarSmartRetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/ai-agents': typeof SidebarAiAgentsRoute
  '/_sidebar/dashboard': typeof SidebarDashboardRoute
  '/_sidebar/dashboards': typeof SidebarDashboardsRoute
  '/_sidebar/decisioning': typeof SidebarDecisioningRoute
  '/_sidebar/declines': typeof SidebarDeclinesRoute
  '/_sidebar/experiments': typeof SidebarExperimentsRoute
  '/_sidebar/incidents': typeof SidebarIncidentsRoute
  '/_sidebar/models': typeof SidebarModelsRoute
  '/_sidebar/notebooks': typeof SidebarNotebooksRoute
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/reason-codes': typeof SidebarReasonCodesRoute
  '/_sidebar/rules': typeof SidebarRulesRoute
  '/_sidebar/setup': typeof SidebarSetupRoute
  '/_sidebar/smart-checkout': typeof SidebarSmartCheckoutRoute
  '/_sidebar/smart-retry': typeof SidebarSmartRetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agents'
    | '/dashboard'
    | '/dashboards'
    | '/decisioning'
    | '/declines'
    | '/experiments'
    | '/incidents'
    | '/models'
    | '/notebooks'
    | '/profile'
    | '/reason-codes'
    | '/rules'
    | '/setup'
    | '/smart-checkout'
    | '/smart-retry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agents'
    | '/dashboard'
    | '/dashboards'
    | '/decisioning'
    | '/declines'
    | '/experiments'
    | '/incidents'
    | '/models'
    | '/notebooks'
    | '/profile'
    | '/reason-codes'
    | '/rules'
    | '/setup'
    | '/smart-checkout'
    | '/smart-retry'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/ai-agents'
    | '/_sidebar/dashboard'
    | '/_sidebar/dashboards'
    | '/_sidebar/decisioning'
    | '/_sidebar/declines'
    | '/_sidebar/experiments'
    | '/_sidebar/incidents'
    | '/_sidebar/models'
    | '/_sidebar/notebooks'
    | '/_sidebar/profile'
    | '/_sidebar/reason-codes'
    | '/_sidebar/rules'
    | '/_sidebar/setup'
    | '/_sidebar/smart-checkout'
    | '/_sidebar/smart-retry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/smart-retry': {
      id: '/_sidebar/smart-retry'
      path: '/smart-retry'
      fullPath: '/smart-retry'
      preLoaderRoute: typeof SidebarSmartRetryRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/smart-checkout': {
      id: '/_sidebar/smart-checkout'
      path: '/smart-checkout'
      fullPath: '/smart-checkout'
      preLoaderRoute: typeof SidebarSmartCheckoutRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/setup': {
      id: '/_sidebar/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SidebarSetupRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/rules': {
      id: '/_sidebar/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof SidebarRulesRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/reason-codes': {
      id: '/_sidebar/reason-codes'
      path: '/reason-codes'
      fullPath: '/reason-codes'
      preLoaderRoute: typeof SidebarReasonCodesRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/notebooks': {
      id: '/_sidebar/notebooks'
      path: '/notebooks'
      fullPath: '/notebooks'
      preLoaderRoute: typeof SidebarNotebooksRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/models': {
      id: '/_sidebar/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof SidebarModelsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/incidents': {
      id: '/_sidebar/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof SidebarIncidentsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/experiments': {
      id: '/_sidebar/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof SidebarExperimentsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/declines': {
      id: '/_sidebar/declines'
      path: '/declines'
      fullPath: '/declines'
      preLoaderRoute: typeof SidebarDeclinesRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/decisioning': {
      id: '/_sidebar/decisioning'
      path: '/decisioning'
      fullPath: '/decisioning'
      preLoaderRoute: typeof SidebarDecisioningRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/dashboards': {
      id: '/_sidebar/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof SidebarDashboardsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/dashboard': {
      id: '/_sidebar/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof SidebarDashboardRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/ai-agents': {
      id: '/_sidebar/ai-agents'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof SidebarAiAgentsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarAiAgentsRoute: typeof SidebarAiAgentsRoute
  SidebarDashboardRoute: typeof SidebarDashboardRoute
  SidebarDashboardsRoute: typeof SidebarDashboardsRoute
  SidebarDecisioningRoute: typeof SidebarDecisioningRoute
  SidebarDeclinesRoute: typeof SidebarDeclinesRoute
  SidebarExperimentsRoute: typeof SidebarExperimentsRoute
  SidebarIncidentsRoute: typeof SidebarIncidentsRoute
  SidebarModelsRoute: typeof SidebarModelsRoute
  SidebarNotebooksRoute: typeof SidebarNotebooksRoute
  SidebarProfileRoute: typeof SidebarProfileRoute
  SidebarReasonCodesRoute: typeof SidebarReasonCodesRoute
  SidebarRulesRoute: typeof SidebarRulesRoute
  SidebarSetupRoute: typeof SidebarSetupRoute
  SidebarSmartCheckoutRoute: typeof SidebarSmartCheckoutRoute
  SidebarSmartRetryRoute: typeof SidebarSmartRetryRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarAiAgentsRoute: SidebarAiAgentsRoute,
  SidebarDashboardRoute: SidebarDashboardRoute,
  SidebarDashboardsRoute: SidebarDashboardsRoute,
  SidebarDecisioningRoute: SidebarDecisioningRoute,
  SidebarDeclinesRoute: SidebarDeclinesRoute,
  SidebarExperimentsRoute: SidebarExperimentsRoute,
  SidebarIncidentsRoute: SidebarIncidentsRoute,
  SidebarModelsRoute: SidebarModelsRoute,
  SidebarNotebooksRoute: SidebarNotebooksRoute,
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarReasonCodesRoute: SidebarReasonCodesRoute,
  SidebarRulesRoute: SidebarRulesRoute,
  SidebarSetupRoute: SidebarSetupRoute,
  SidebarSmartCheckoutRoute: SidebarSmartCheckoutRoute,
  SidebarSmartRetryRoute: SidebarSmartRetryRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
